// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOICx0KFNW-lEmwqrhzzmbiwf67tE6Qk',
    appId: '1:830354761125:web:2a284e93fcff394981f44c',
    messagingSenderId: '830354761125',
    projectId: 'swinburne-kch-iot',
    authDomain: 'swinburne-kch-iot.firebaseapp.com',
    storageBucket: 'swinburne-kch-iot.firebasestorage.app',
    measurementId: 'G-M3BGZV77HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYMybF1IaiT56bLKjVpM5XJiEXbA-ZBY',
    appId: '1:830354761125:android:a06f7f4869c06c5a81f44c',
    messagingSenderId: '830354761125',
    projectId: 'swinburne-kch-iot',
    storageBucket: 'swinburne-kch-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY7skEm7IRnTpOh1bzAhR_Vnb8bCddido',
    appId: '1:830354761125:ios:0d1c03c26cf74ffb81f44c',
    messagingSenderId: '830354761125',
    projectId: 'swinburne-kch-iot',
    storageBucket: 'swinburne-kch-iot.firebasestorage.app',
    iosBundleId: 'com.example.nekoNekoNya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY7skEm7IRnTpOh1bzAhR_Vnb8bCddido',
    appId: '1:830354761125:ios:0d1c03c26cf74ffb81f44c',
    messagingSenderId: '830354761125',
    projectId: 'swinburne-kch-iot',
    storageBucket: 'swinburne-kch-iot.firebasestorage.app',
    iosBundleId: 'com.example.nekoNekoNya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkOICx0KFNW-lEmwqrhzzmbiwf67tE6Qk',
    appId: '1:830354761125:web:39b387d9b3b378cb81f44c',
    messagingSenderId: '830354761125',
    projectId: 'swinburne-kch-iot',
    authDomain: 'swinburne-kch-iot.firebaseapp.com',
    storageBucket: 'swinburne-kch-iot.firebasestorage.app',
    measurementId: 'G-XNRDG8GY90',
  );
}
